### ISSUE TITLE
ХОХЛЫ СЛОМАЛИ МОЙ ПК!

### ISSUE THREAD

**Issue by nevadimov** [aweone/HarderBetterFasterStronger#1]
ИЗ ЗА ЭТОГО ПРИЛОЖЕНИЯ ХОХЛЫ СЛОМАЛИ МНЕ ПК ПОМОГИТЕ ПЖ Я ПОДАРЮ 1050 ТИАЙ

**Comment by aweone** [comment]
МОЙ ПК ТОЖЕ СЛОМАЛСЯ ПОМОГИТЕ ПЖПЖПЖ У МЕНЯ ИНТЕЛ КСЕНОН Е5450 ГТ7100

**Comment by nevadimov** [comment]
я понял надо пк купить всё решил спасибо всем кто помогал а главное берегите своих родных

**Comment by aweone** [comment]
берегите себя и своих близких, до свидания!
